;;;; package.lisp

(defpackage #:wimelib-sqlite3
  (:use #:cl #:cffi #:alexandria #:wimelib-sql #:closer-mop)
  (:shadowing-import-from #:closer-mop
			  #:standard-method
			  #:standard-generic-function
			  #:defmethod
			  #:defgeneric
			  #:standard-class)
  (:export
   +sqlite3-ok+
   +sqlite3-error+
   +sqlite3-internal+
   +sqlite3-perm+
   +sqlite3-abort+
   +sqlite3-busy+
   +sqlite3-locked+
   +sqlite3-nomem+
   +sqlite3-readonly+
   +sqlite3-interrupt+
   +sqlite3-ioerr+
   +sqlite3-corrupt+
   +sqlite3-notfound+
   +sqlite3-full+
   +sqlite3-cantopen+
   +sqlite3-protocol+
   +sqlite3-empty+
   +sqlite3-schema+
   +sqlite3-toobig+
   +sqlite3-constraint+
   +sqlite3-mismatch+
   +sqlite3-misuse+
   +sqlite3-nolfs+
   +sqlite3-auth+
   +sqlite3-format+
   +sqlite3-range+
   +sqlite3-notadb+
   +sqlite3-row+
   +sqlite3-done+
   sqlite3-error-condition
   sqlite3-open
   sqlite3-close
   sqlite3-prepare
   sqlite3-step
   sqlite3-column-blob
   sqlite3-column-bytes
   sqlite3-column-float
   sqlite3-column-integer
   sqlite3-column-text
   +sqlite3-integer+
   +sqlite3-float+
   +sqlite3-text+
   +sqlite3-blob+
   +sqlite3-null+
   sqlite3-column-type
   sqlite3-column-name
   sqlite3-data-count
   define-bind-destructor
   sqlite3-bind-blob
   +bind-destructor-static+
   +bind-destructor-transient+
   sqlite3-bind-float
   sqlite3-bind-integer
   sqlite3-bind-null
   sqlite3-bind-text
   sqlite3-bind-parameter-index
   sqlite3-bind-parameter-count
   sqlite3-bind-parameter-name
   sqlite3-clear-bindings
   sqlite3-reset
   sqlite3-finalize
   sqlite3-do-rows
   sqlite3-exec
   sqlite3-row-values
   sqlite3-column-names
   sqlite3-dump-table
   ;; the official interface
   ssql
   ssql*
   open-db
   close-db
   with-db
   with-open-db
   column-value
   column-values
   exec
   do-rows
   do-query
   map-query
   query
   begin-transaction
   commit-transaction
   savepoint
   release-savepoint
   rollback
   with-transaction
   with-savepoint
   list-tables
   table-exists-p
   list-indices
   attribute-list
   attribute-name
   attribute-type
   defprepared
   prepare
   prepared-results
   enable-bind-reader-syntax
   disable-bind-reader-syntax
   da-class
   table-name
   insert-da
   update-record
   refresh-da
   delete-da
   get-da
   all-das
   ))

